FROM bitnami/minideb:bookworm

ARG userid
ARG groupid

RUN mkdir -p /app

COPY scripts/group_init.bsh /usr/local/bin
COPY scripts/user_init.bsh /usr/local/bin
COPY scripts/pipx_init.bsh /usr/local/bin

RUN group_init.bsh $groupid
RUN user_init.bsh $userid $groupid

RUN chown -R $userid:$groupid /app
WORKDIR /app

RUN install_packages python3-full pipx curl

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash
RUN install_packages nodejs

USER $userid
RUN pipx_init.bsh $userid
