# Generated by Django 5.0.6 on 2024-05-23 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darulez', '0002_application_status_alter_documentrule_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='darulez.documentrule'),
            preserve_default=False,
        ),
    ]
